apiVersion: v1
kind: Service              # 1
metadata:
  name: frontend
spec:
  ports:
  - port: 8080               # 3
    protocol: TCP          # 4
    targetPort: 8080         # 5
  selector:                # 6
    app: sa-frontend       # 7
